### ISSUE TITLE
-i option not working

### ISSUE THREAD

**Issue by tmigone** [balena-io/takeover#3]
User reports that they can't pass image to the binary using `-i`. Allowing the app to download the image worked though.

See: https://jel.ly.fish/d3affa97-4be5-4c03-8294-f2d95037bcc6

**Comment by samothx** [comment]
As far as I can see this is works as designed. The readme for this project is currently in the making and will explain this. 
This customer tried to use flasher images downloaded from the dashboard to migrate a device. Flasher images are different from the actual balena image - they contain the actual image though. To use the -i option you need a non-flasher balena-os image compressed with gzip. 
It sounds like this customer tried too, to gzip compress his image and use that.  That should have worked but he would still have flashed a flasher image which would not have given him a running balena device.
